language: node_js
node_js:
 - "node"

jobs:
 include:
  - dist: focal
    arch: amd64
    script:
     - node hello_world.js
  - dist: focal
    arch: ppc64le
    script:
     - node hello_world.js
  - dist: xenial
    arch: amd64
    script:
     - node hello_world.js
  - dist: xenial
    arch: ppc64le
    script:
     - node hello_world.js
  - dist: bionic
    arch: amd64
    script:
     - node hello_world.js
  - dist: bionic
    arch: ppc64le
    script:
     - node hello_world.js
